
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://192.168.49.2:8443
  name: test
contexts:
- context:
    cluster: test
    namespace: default
    user: experimenter
  name: exp-test
current-context: exp-test
kind: Config
preferences: {}
users:
- name: experimenter
  user:
    password: testmesh
    username: exp-test