name: Lint and unit tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Run golangci-lint
        run: make check
  tidy:
    name: tidy
    needs: [golangci]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: '1.21'
      - name: go mod tidy
        run: make tidy
  tests:
     name: Tests
     needs: [tidy]
     runs-on: ubuntu-latest
     env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: true
     steps:
     - name: Check out code
       uses: actions/checkout@master
       with:
        fetch-depth: 1
     - name: Setup Go
       uses: actions/setup-go@master
       with:
        go-version: 1.21
     - run: make test
  codecov: 
     needs: [golangci, tidy]
     name: Code Coverage
     if: github.repository == 'meshery/meshkit'
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout code
         uses: actions/checkout@master
       - name: Set up Go
         uses:  actions/setup-go@v4
         with: 
           go-version: 1.21
           cache: true
           cache-dependency-path: go.sum
       - name: Run unit tests
         run: make test
       - name: Upload coverage to Codecov
         if: github.repository == 'meshery/meshery-operator'
         uses: codecov/codecov-action@v3
         with:
             files: ./coverage.txt
             flags: unittests    
